-- Seed Amenities for RoomLagbe
-- Run this after schema setup to populate amenity master list

-- Clear existing amenities (if any) - using DELETE instead of TRUNCATE
DELETE FROM room_amenity;
DELETE FROM apartment_amenity;
DELETE FROM amenity;

-- Insert common amenities 
-- amenity_id will be auto-generated by gen_random_uuid()
INSERT INTO amenity (name) VALUES
  ('WiFi'),
  ('Air Conditioning'),
  ('Generator/IPS'),
  ('Lift/Elevator'),
  ('Parking'),
  ('Security Guard'),
  ('CCTV Surveillance'),
  ('Gas Connection'),
  ('Water Supply 24/7'),
  ('Backup Water Supply'),
  ('Attached Bathroom'),
  ('Western Toilet'),
  ('Balcony'),
  ('Kitchen'),
  ('Furnished'),
  ('Semi-Furnished'),
  ('Washing Machine'),
  ('Refrigerator'),
  ('Study Table'),
  ('Bed'),
  ('Wardrobe'),
  ('TV'),
  ('Microwave'),
  ('Rice Cooker'),
  ('Prayer Room'),
  ('Rooftop Access'),
  ('Garage'),
  ('Garden/Lawn'),
  ('Intercom System'),
  ('Fire Safety System');

-- Display count
SELECT COUNT(*) AS total_amenities FROM amenity;
